name: mqtt_client_example
description: Demonstrates how to use mqtt_client with flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  crypto: ^2.0.6
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  image_picker:  0.4.12+1
  font_awesome_flutter: ^8.2.0
  mqtt_client: ^5.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
